version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8443:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
