# TODO create dev and prod profiles
# TODO use environment variables instead of hardcoding stuff


spring:
  application:
    name: udas-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://0.0.0.0:8443
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  sql:
    init:
      mode: always

server:
  port: 9001